export * from './controllers/arquivo.controller.js'
export * from './controllers/asset-type.controller.js'
export * from './controllers/generate-index.controller.js'
export * from './controllers/gifs.controller.js'
export * from './controllers/profile.controller.js'
export * from './controllers/recs.controller.js'
export * from './controllers/recs25.controller.js'
export * from './scripts/generate-index.script.js'
